set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#317C75 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#98999A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#98999A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Conceal guifg=#878787 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#317C75 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#030303 guibg=#C1C2C3 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#98999A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=#878787 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight CursorLineNr guifg=#030303 guibg=#C1C2C3 guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#5D5E69 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#595A64 guibg=NONE guisp=#595A64 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#199A84 guibg=NONE guisp=#199A84 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#7E817F guibg=NONE guisp=#7E817F blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#0D8C77 guibg=NONE guisp=#0D8C77 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#83510C guibg=#878787 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#ADADAE guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#595A64 guibg=#878787 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#595A64 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#7E817F guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#83510C guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#7E817F guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#595A64 guibg=#C1C2C3 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#595A64 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#317C75 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#7E817F guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#878787 guibg=#317C75 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#ADADAE guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C1C2C3 guibg=#ADADAE guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#878787 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#7E817F guibg=NONE guisp=#ADADAE blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#5D5E69 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#5D5E69 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#0D8C77 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#98999A guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#030303 guibg=#199A84 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#030303 guibg=#7E817F guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#030303 guibg=#83510C guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#030303 guibg=#B9BABB guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#030303 guibg=#595A64 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#030303 guibg=#317C75 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#878787 guibg=#317C75 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#ADADAE guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#83510C guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#98999A guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#ADADAE guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#595A64 guibg=#C1C2C3 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#ADADAE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#317C75 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C1C2C3 guibg=#7E817F guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#98999A guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#ADADAE guibg=#0D8C77 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#98999A guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#5D5E69 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#ADADAE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#595A64 guibg=NONE guisp=#595A64 blend=NONE gui=underline
highlight SpellCap guifg=#0D8C77 guibg=NONE guisp=#0D8C77 blend=NONE gui=underline
highlight SpellLocal guifg=#199A84 guibg=NONE guisp=#199A84 blend=NONE gui=underline
highlight SpellRare guifg=#B9BABB guibg=NONE guisp=#B9BABB blend=NONE gui=underline
highlight Statement guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C1C2C3 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#98999A guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#83510C guibg=#83510C guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#0D8C77 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#ADADAE guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#ADADAE guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#83510C guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#317C75 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#0D8C77 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Typedef guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#030303 guibg=#98999A guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C1C2C3 guibg=#7E817F guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C1C2C3 guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#98999A guibg=#030303 guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#5D5E69 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C1C2C3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#5D5E69 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#83510C guibg=#878787 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#595A64 guibg=#878787 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#B9BABB guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#83510C guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#199A84 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#0D8C77 guibg=#878787 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#878787 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#7E817F guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#0D8C77 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#595A64 guibg=NONE guisp=NONE blend=NONE gui=NONE
