set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#5983A6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#97A4AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#97A4AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Conceal guifg=#868F98 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#5983A6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#04060C guibg=#C3CFDA guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#97A4AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=#868F98 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight CursorLineNr guifg=#04060C guibg=#C3CFDA guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#5E82A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#5D7C98 guibg=NONE guisp=#5D7C98 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#8A9CAD guibg=NONE guisp=#8A9CAD blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#6B91B3 guibg=NONE guisp=#6B91B3 blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#5588AF guibg=NONE guisp=#5588AF blend=NONE gui=underline
highlight DiagnosticWarn guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#758799 guibg=#868F98 guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#ABB8C4 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#5D7C98 guibg=#868F98 guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#5D7C98 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#6B91B3 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#758799 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#6B91B3 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#5D7C98 guibg=#C3CFDA guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#5D7C98 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#5983A6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#6B91B3 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=italic
highlight Function guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#868F98 guibg=#5983A6 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#ABB8C4 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#C3CFDA guibg=#ABB8C4 guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#868F98 guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#6B91B3 guibg=NONE guisp=#ABB8C4 blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#5E82A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#5E82A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#5588AF guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#97A4AF guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#04060C guibg=#8A9CAD guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#04060C guibg=#6B91B3 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#04060C guibg=#758799 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#04060C guibg=#C4AED5 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#04060C guibg=#5D7C98 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#04060C guibg=#5983A6 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#868F98 guibg=#5983A6 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#ABB8C4 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#758799 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#97A4AF guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#ABB8C4 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#5D7C98 guibg=#C3CFDA guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#ABB8C4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#5983A6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#C3CFDA guibg=#6B91B3 guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#97A4AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#ABB8C4 guibg=#5588AF guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#97A4AF guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#5E82A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#ABB8C4 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#5D7C98 guibg=NONE guisp=#5D7C98 blend=NONE gui=underline
highlight SpellCap guifg=#5588AF guibg=NONE guisp=#5588AF blend=NONE gui=underline
highlight SpellLocal guifg=#8A9CAD guibg=NONE guisp=#8A9CAD blend=NONE gui=underline
highlight SpellRare guifg=#C4AED5 guibg=NONE guisp=#C4AED5 blend=NONE gui=underline
highlight Statement guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#C3CFDA guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#97A4AF guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#758799 guibg=#758799 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#5588AF guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#ABB8C4 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#ABB8C4 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#758799 guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#5983A6 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#5588AF guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Typedef guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#04060C guibg=#97A4AF guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#C3CFDA guibg=#6B91B3 guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#C3CFDA guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#97A4AF guibg=#04060C guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#5E82A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#C3CFDA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#5E82A1 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#758799 guibg=#868F98 guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#5D7C98 guibg=#868F98 guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#C4AED5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#758799 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#8A9CAD guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#5588AF guibg=#868F98 guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#868F98 guisp=NONE blend=NONE gui=underline
highlight @type guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#6B91B3 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#5588AF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#5D7C98 guibg=NONE guisp=NONE blend=NONE gui=NONE
